name: Hello World Program

on: [push, pull_request]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v4
      - name: Build the code
        run: |
          make -j2
      - name: Upload built application
        uses: actions/upload-artifact@v4
        with:
          name: built-artifact
          path: hello
